# Generated by Django 5.2.15 on 2026-08-04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more")]

    operations = [
        migrations.CreateModel(
            name="WorkspaceSchedulerSettings",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("google_calendar_embed_url", models.URLField(blank=True, default="")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to="db.user", verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to="db.user", verbose_name="Last Modified By")),
                ("workspace", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="scheduler_settings", to="db.workspace")),
            ],
            options={"db_table": "workspace_scheduler_settings"},
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("content_type", models.CharField(choices=[("issue", "Issue"), ("comment", "Comment")], max_length=20)),
                ("content_id", models.UUIDField(db_index=True)),
                ("field", models.CharField(default="body", max_length=30)),
                ("original_text", models.TextField()),
                ("source_language", models.CharField(blank=True, default="", max_length=12)),
                ("translated_text", models.TextField(blank=True, default="")),
                ("target_language", models.CharField(max_length=12)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed"), ("skipped", "Skipped")], default="pending", max_length=20)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to="db.user", verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to="db.user", verbose_name="Last Modified By")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="db.workspace")),
            ],
            options={"db_table": "translations"},
        ),
        migrations.AddConstraint(model_name="translation", constraint=models.UniqueConstraint(fields=("content_type", "content_id", "field", "target_language"), name="translation_content_field_language_unique")),
        migrations.AddIndex(model_name="translation", index=models.Index(fields=["workspace", "content_type", "content_id"], name="translation_workspa_487077_idx")),
    ]
